/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.ows11.validation;

import net.opengis.ows11.CodeType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.ows11.DatasetDescriptionSummaryBaseType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DatasetDescriptionSummaryBaseTypeValidator {
    boolean validate();

    boolean validateWGS84BoundingBox(EList value);
    boolean validateIdentifier(CodeType value);
    boolean validateBoundingBoxGroup(FeatureMap value);
    boolean validateBoundingBox(EList value);
    boolean validateMetadata(EList value);
    boolean validateDatasetDescriptionSummary(EList value);
}
