/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.ows11.validation;

import net.opengis.ows11.OnlineResourceType;
import net.opengis.ows11.ResponsiblePartySubsetType;

/**
 * A sample validator interface for {@link net.opengis.ows11.ServiceProviderType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceProviderTypeValidator {
    boolean validate();

    boolean validateProviderName(String value);
    boolean validateProviderSite(OnlineResourceType value);
    boolean validateServiceContact(ResponsiblePartySubsetType value);
}
