/**
 *
 * $Id$
 */
package net.opengis.ows11.validation;

import net.opengis.ows11.CodeType;

/**
 * A sample validator interface for {@link net.opengis.ows11.ServiceIdentificationType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceIdentificationTypeValidator {
  boolean validate();

  boolean validateServiceType(CodeType value);
  boolean validateServiceTypeVersion(String value);
  boolean validateProfile(String value);
  boolean validateFees(String value);
  boolean validateAccessConstraints(String value);
}
