<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wfsv"
    nsURI="http://www.opengis.net/wfsv" nsPrefix="wfsv">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractVersionedFeatureType" abstract="true">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="AbstractVersionedFeatureType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="version"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="author"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="date"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="message"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribeVersionedFeatureTypeType" eSuperTypes="wfs.ecore#//DescribeFeatureTypeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xD;&#xA;            Same as wfs:DescribeFeatureType, but with the option to output&#xD;&#xA;            a versioned feature type instead of a plain one&#xD;&#xA;         "/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DescribeVersionedFeatureTypeType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versioned" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;                     If false, the output is the same as wfs:DescribeFeatureType,&#xD;&#xA;                     if true on the contrary the generated feature type will descend&#xD;&#xA;                     form wfsv:AbstractVersionedFeatureType&#xD;&#xA;                  "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="versioned"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifferenceQueryType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DifferenceQueryType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;            The Filter element is used to define spatial and/or non-spatial constraints on query.&#xD;&#xA;            Spatial constrains use GML3 to specify the constraining geometry. A full description of&#xD;&#xA;            the Filter element can be found in the Filter Encoding Implementation Specification.&#xD;&#xA;          "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Filter"/>
        <details key="namespace" value="http://www.opengis.net/ogc"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromFeatureVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="FIRST" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;          Same as featureVersion in QueryType, but this indicates a starting feature version for a&#xD;&#xA;          difference and log operations.&#xD;&#xA;        "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="fromFeatureVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srsName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;          This attribute is used to specify a specific WFS-supported SRS that should be used for&#xD;&#xA;          returned feature geometries. The value may be the WFS StorageSRS value,&#xD;&#xA;          DefaultRetrievalSRS value, or one of AdditionalSRS values. If no srsName value is&#xD;&#xA;          supplied, then the features will be returned using either the DefaultRetrievalSRS, if&#xD;&#xA;          specified, and StorageSRS otherwise. For feature types with no spatial properties, this&#xD;&#xA;          attribute must not be specified or ignored if it is specified.&#xD;&#xA;        "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="srsName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toFeatureVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="LAST" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;          Same as featureVersion in QueryType, indicates the second version to be used for&#xD;&#xA;          performing a difference of log operation.&#xD;&#xA;        "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="toFeatureVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//QName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;          The typeName attribute is a single feature type name that indicates which type of feature&#xD;&#xA;          instances should be included in the reponse set. The names must be a valid type that&#xD;&#xA;          belong to this query's feature content as defined by the GML Application Schema.&#xD;&#xA;        "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="typeName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value=""/>
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="elementWildcard"/>
        <details key="name" value=":mixed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xmlns:prefix"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="xsi:schemaLocation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="describeVersionedFeatureType"
        unique="false" upperBound="-2" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;            Same as wfs:DescribeFeatureType, but with the option to output&#xD;&#xA;            a versioned feature type instead of a plain one&#xD;&#xA;         "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DescribeVersionedFeatureType"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="affiliation" value="http://www.opengis.net/wfs#DescribeFeatureType"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="differenceQuery" upperBound="-2"
        eType="#//DifferenceQueryType" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;        The DifferenceFilter element is used to gather differences in features matched by a standard&#xD;&#xA;        OGC filter at starting and ending featureVersion, and a filter used to match&#xD;&#xA;      "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DifferenceQuery"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="getDiff" upperBound="-2"
        eType="#//GetDiffType" volatile="true" transient="true" derived="true" containment="true"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;        The GetDiff element is used to request that a Versioning Web Feature Service returns a&#xD;&#xA;        transaction command that can be used to alter features at version m to turn them into&#xD;&#xA;        version n&#xD;&#xA;      "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="GetDiff"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="getLog" upperBound="-2"
        eType="#//GetLogType" volatile="true" transient="true" derived="true" containment="true"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;        The GetLog element is used to request that a Versioning Web Feature Service return the&#xD;&#xA;        change history for features of one or more feature types.&#xD;&#xA;      "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="GetLog"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="getVersionedFeature" upperBound="-2"
        eType="#//GetVersionedFeatureType" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;            The GetVersionedFeature element is used to request that a Versioning &#xD;&#xA;            Web Feature Service return versioned feature type instances &#xD;&#xA;            of one or more feature types.&#xD;&#xA;         "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="GetVersionedFeature"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="affiliation" value="http://www.opengis.net/wfs#GetFeature"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rollback" upperBound="-2"
        eType="#//RollbackType" volatile="true" transient="true" derived="true" containment="true"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;        Rolls back the changes occurred on all matched features between fromFeatureVersion and&#xD;&#xA;        featureVersion&#xD;&#xA;      "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Rollback"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="affiliation" value="http://www.opengis.net/wfs#Native"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionedDelete" upperBound="-2"
        eType="#//VersionedDeleteElementType" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="VersionedDelete"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="affiliation" value="http://www.opengis.net/wfs#Delete"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionedFeatureCollection"
        upperBound="-2" eType="#//VersionedFeatureCollectionType" volatile="true"
        transient="true" derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="VersionedFeatureCollection"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="affiliation" value="http://www.opengis.net/wfs#FeatureCollection"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionedUpdate" upperBound="-2"
        eType="#//VersionedUpdateElementType" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="VersionedUpdate"/>
        <details key="namespace" value="##targetNamespace"/>
        <details key="affiliation" value="http://www.opengis.net/wfs#Update"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetDiffType" eSuperTypes="wfs.ecore#//BaseRequestType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xD;&#xA;        A GetDiff element contains one or more DifferenceQuery elements that describe a difference&#xD;&#xA;        query operation on one feature type. In response to a GetDiff request, a Versioning Web&#xD;&#xA;        Feature Service must be able to generate a Transaction command that can be used to alter&#xD;&#xA;        features at fromFeatureVersion and alter them into features at toFeatureVersion&#xD;&#xA;      "/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="GetDiffType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="differenceQuery" lowerBound="1"
        upperBound="-1" eType="#//DifferenceQueryType" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;        The DifferenceFilter element is used to gather differences in features matched by a standard&#xD;&#xA;        OGC filter at starting and ending featureVersion, and a filter used to match&#xD;&#xA;      "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DifferenceQuery"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="text/xml; subtype=wfs-transaction/1.1.0" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              The outputFormat attribute is used to specify the output format that the Versioning&#xD;&#xA;              Web Feature Service should generate in response to a GetDiff element. The default&#xD;&#xA;              value of 'application/xml; subtype=wfsv-transaction/1.1.0' indicates that the output&#xD;&#xA;              is an XML document that conforms to the WFS 1.1.0 Transaction definition. For the&#xD;&#xA;              purposes of experimentation, vendor extension, or even extensions that serve a&#xD;&#xA;              specific community of interest, other acceptable output format values may be used to&#xD;&#xA;              specify other formats as long as those values are advertised in the capabilities&#xD;&#xA;              document.&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="outputFormat"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetLogType" eSuperTypes="wfs.ecore#//BaseRequestType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xD;&#xA;        A GetLog element contains one or more DifferenceQuery elements that describe a diffence&#xD;&#xA;        query operation on one feature type. In response to a GetLog request, a Web Feature Service&#xD;&#xA;        must be able to generate a list of logs entries for features matched by the DifferenceQuery&#xD;&#xA;        parameters. Each log entry is an instance of the ChangeSet feature type. In response to a&#xD;&#xA;        GetFeature request, a Versioning Web Feature Service must be able to generate a GML3&#xD;&#xA;        response that validates using a schema generated by the DescribeFeatureType request against&#xD;&#xA;        the ChangeSets feature type. A Web Feature Service may support other possibly non-XML (and&#xD;&#xA;        even binary) output formats as long as those formats are advertised in the capabilities&#xD;&#xA;        document.&#xD;&#xA;      "/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="GetLogType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="differenceQuery" lowerBound="1"
        upperBound="-1" eType="#//DifferenceQueryType" containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;        The DifferenceFilter element is used to gather differences in features matched by a standard&#xD;&#xA;        OGC filter at starting and ending featureVersion, and a filter used to match&#xD;&#xA;      "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="DifferenceQuery"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxFeatures" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//PositiveInteger">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              The maxFeatures attribute is used to specify the maximum number of features that a&#xD;&#xA;              GetFeature operation should generate (regardless of the actual number of query hits).&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="maxFeatures"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="text/xml; subtype=gml/3.1.1" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              The outputFormat attribute is used to specify the output format that the Versioning&#xD;&#xA;              Web Feature Service should generate in response to a GetLog element. The default value&#xD;&#xA;              of 'text/xml; subtype=gml/3.1.1' indicates that the output is an XML document that&#xD;&#xA;              conforms to the Geography Markup Language (GML) Implementation Specification V3.1.1.&#xD;&#xA;              For the purposes of experimentation, vendor extension, or even extensions that serve a&#xD;&#xA;              specific community of interest, other acceptable output format values may be used to&#xD;&#xA;              specify other formats as long as those values are advertised in the capabilities&#xD;&#xA;              document.&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="outputFormat"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultType" eType="ecore:EEnum wfs.ecore#//ResultTypeType"
        defaultValueLiteral="results" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              The resultType attribute is used to indicate what response a wfsv should return to&#xD;&#xA;              user once a GetFeature request is processed. Possible values are: results - meaning&#xD;&#xA;              that the full response set (i.e. all the feature instances) should be returned. hits -&#xD;&#xA;              meaning that an empty response set should be returned (i.e. no feature instances&#xD;&#xA;              should be returned) but the &quot;numberOfFeatures&quot; attribute should be set to the number&#xD;&#xA;              of feature instances that would be returned.&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="resultType"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetVersionedFeatureType" eSuperTypes="wfs.ecore#//GetFeatureType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xD;&#xA;        The GetVersionedFeature extends GetFeature by returning a collection&#xD;&#xA;        of AbstractVersionedFeature, which do contain more information about&#xD;&#xA;        the last change occurred on each feature.&#xD;&#xA;      "/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="GetVersionedFeatureType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RollbackType" eSuperTypes="wfs.ecore#//NativeType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="RollbackType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;                The Filter element is used to define spatial and/or non-spatial constraints on&#xD;&#xA;                query. Spatial constrains use GML3 to specify the constraining geometry. A full&#xD;&#xA;                description of the Filter element can be found in the Filter Encoding Implementation&#xD;&#xA;                Specification.&#xD;&#xA;              "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Filter"/>
        <details key="namespace" value="http://www.opengis.net/ogc"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="handle" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              The handle attribute allows a client application to assign a client-generated request&#xD;&#xA;              identifier to an Insert action. The handle is included to facilitate error reporting.&#xD;&#xA;              If a Rollback action in a Transaction request fails, then a Versioning WFS may include&#xD;&#xA;              the handle in an exception report to localize the error. If no handle is included of&#xD;&#xA;              the offending Rollback element then a WFS may employee other means of localizing the&#xD;&#xA;              error (e.g. line number).&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="handle"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toFeatureVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="FIRST" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              Same as featureVersion in QueryType. Rollback will restore the &quot;toFeatureVersion&quot; &#xD;&#xA;              feature state, removing all changes occurred between &quot;toFeatureVersion&quot; and current&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="toFeatureVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//QName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              The typeName attribute is a single feature type name that indicates which type of&#xD;&#xA;              feature instances should be included in the reponse set. The names must be a valid&#xD;&#xA;              type that belong to this query's feature content as defined by the GML Application&#xD;&#xA;              Schema.&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="typeName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral="" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              User id to be used in addition to the filter in order to isolate the features to be&#xD;&#xA;              rolled back. Only the features modified by the specified user between&#xD;&#xA;              fromFeatureVersion and the current version will be subjected to roll back.&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="user"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedDeleteElementType" eSuperTypes="wfs.ecore#//DeleteElementType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VersionedDeleteElementType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureVersion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              See VersionedUpdateElementType featureVersion attribute.&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="featureVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedFeatureCollectionType" eSuperTypes="wfs.ecore#//FeatureCollectionType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A collection of versioned features"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VersionedFeatureCollectionType"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="version"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedUpdateElementType" eSuperTypes="wfs.ecore#//UpdateElementType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VersionedUpdateElementType"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureVersion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xD;&#xA;              The syntax and semantics is the same as featureVersion in Query. If specified, update&#xD;&#xA;              will check that every updated feature is still at the specified version before&#xD;&#xA;              executing, and will fail if a change occurred on the server in the meantime.&#xD;&#xA;            "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="featureVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
