/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 *
 *    (C) 2002-2026, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.data.duckdb;

import java.util.Map;
import org.geotools.jdbc.JDBCDataStoreFactory;
import org.geotools.jdbc.JDBCPrimaryKeyOnlineTest;
import org.geotools.jdbc.JDBCPrimaryKeyTestSetup;
import org.junit.Ignore;
import org.junit.Test;

public class DuckDBPrimaryKeyOnlineTest extends JDBCPrimaryKeyOnlineTest {
    private static final String AUTO_INCREMENT_METADATA_UNSUPPORTED =
            "DuckDB JDBC does not expose auto-increment metadata for primary key columns";
    private static final String INDEX_METADATA_COLUMNS_UNSUPPORTED =
            "DuckDB JDBC getIndexInfo() does not expose indexed column names needed by the generic finder";

    @Override
    protected JDBCPrimaryKeyTestSetup createTestSetup() {
        return new DuckDBPrimaryKeyTestSetup();
    }

    @Override
    protected Map<String, Object> createDataStoreFactoryParams() throws Exception {
        Map<String, Object> params = super.createDataStoreFactoryParams();
        params.put(AbstractDuckDBDataStoreFactory.READ_ONLY.key, Boolean.FALSE);
        params.put(JDBCDataStoreFactory.BATCH_INSERT_SIZE.key, 1);
        return params;
    }

    @Override
    @Test
    @Ignore(AUTO_INCREMENT_METADATA_UNSUPPORTED)
    public void testAutoGeneratedPrimaryKey() throws Exception {
        // Ignored on purpose. See @Ignore reason.
    }

    @Override
    @Test
    @Ignore(INDEX_METADATA_COLUMNS_UNSUPPORTED)
    public void testUniqueIndex() throws Exception {
        // Ignored on purpose. See @Ignore reason.
    }
}
