/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import net.opengis.wfs20.SimpleFeatureCollectionType;
import net.opengis.wfs20.ValueCollectionType;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.wfs20.AdditionalObjectsType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdditionalObjectsTypeValidator {
  boolean validate();

  boolean validateValueCollection(ValueCollectionType value);
  boolean validateSimpleFeatureCollectionGroup(FeatureMap value);
  boolean validateSimpleFeatureCollection(SimpleFeatureCollectionType value);
}
