/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.opengis.filter.identity.FeatureId;

/**
 * A sample validator interface for {@link net.opengis.wfs20.FeaturesLockedType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeaturesLockedTypeValidator {
  boolean validate();

  boolean validateGroup(FeatureMap value);
  boolean validateResourceId(EList<FeatureId> value);
}
