/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import java.math.BigInteger;

import net.opengis.fes20.AbstractQueryExpressionType;

import net.opengis.wfs20.ResolveValueType;
import net.opengis.wfs20.ResultTypeType;

/**
 * A sample validator interface for {@link net.opengis.wfs20.GetPropertyValueType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GetPropertyValueTypeValidator {
  boolean validate();

  boolean validateAbstractQueryExpression(AbstractQueryExpressionType value);
  boolean validateCount(BigInteger value);
  boolean validateOutputFormat(String value);
  boolean validateResolve(ResolveValueType value);
  boolean validateResolveDepth(String value);
  boolean validateResolvePath(String value);
  boolean validateResolveTimeout(BigInteger value);
  boolean validateResultType(ResultTypeType value);
  boolean validateStartIndex(BigInteger value);
  boolean validateValueReference(String value);
}
