/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import java.math.BigInteger;

import net.opengis.fes20.AbstractQueryExpressionType;

import net.opengis.wfs20.AllSomeType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.wfs20.LockFeatureType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LockFeatureTypeValidator {
  boolean validate();

  boolean validateAbstractQueryExpressionGroup(FeatureMap value);
  boolean validateAbstractQueryExpression(EList<AbstractQueryExpressionType> value);
  boolean validateExpiry(BigInteger value);
  boolean validateLockAction(AllSomeType value);
  boolean validateLockId(String value);
}
