/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import net.opengis.wfs20.SimpleFeatureCollectionType;
import net.opengis.wfs20.TupleType;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.w3.xlink.ActuateType;
import org.w3.xlink.ShowType;

/**
 * A sample validator interface for {@link net.opengis.wfs20.MemberPropertyType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemberPropertyTypeValidator {
  boolean validate();

  boolean validateMixed(FeatureMap value);
  boolean validateAny(FeatureMap value);
  boolean validateTuple(TupleType value);
  boolean validateSimpleFeatureCollectionGroup(FeatureMap value);
  boolean validateSimpleFeatureCollection(SimpleFeatureCollectionType value);
  boolean validateActuate(ActuateType value);
  boolean validateArcrole(String value);
  boolean validateHref(String value);
  boolean validateRole(String value);
  boolean validateShow(ShowType value);
  boolean validateState(Object value);
  boolean validateTitle(String value);
  boolean validateType(String value);
}
