/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import java.math.BigInteger;

import javax.xml.namespace.QName;

import net.opengis.wfs20.ResolveValueType;

/**
 * A sample validator interface for {@link net.opengis.wfs20.PropertyNameType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyNameTypeValidator {
  boolean validate();

  boolean validateValue(QName value);
  boolean validateResolve(ResolveValueType value);
  boolean validateResolveDepth(Object value);
  boolean validateResolvePath(String value);
  boolean validateResolveTimeout(BigInteger value);
}
