/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import java.util.List;

import javax.xml.namespace.QName;

/**
 * A sample validator interface for {@link net.opengis.wfs20.QueryExpressionTextType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QueryExpressionTextTypeValidator {
  boolean validate();

  boolean validateIsPrivate(boolean value);
  boolean validateLanguage(String value);
  boolean validateReturnFeatureTypes(List<QName> value);
  boolean validateValue(String value);
}
