/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import net.opengis.ows11.MetadataType;

import net.opengis.wfs20.AbstractType;
import net.opengis.wfs20.ParameterExpressionType;
import net.opengis.wfs20.QueryExpressionTextType;
import net.opengis.wfs20.TitleType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wfs20.StoredQueryDescriptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StoredQueryDescriptionTypeValidator {
  boolean validate();

  boolean validateTitle(EList<TitleType> value);
  boolean validateAbstract(EList<AbstractType> value);
  boolean validateMetadata(EList<MetadataType> value);
  boolean validateParameter(EList<ParameterExpressionType> value);
  boolean validateQueryExpressionText(EList<QueryExpressionTextType> value);
  boolean validateId(String value);
}
