/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import net.opengis.wfs20.ActionResultsType;
import net.opengis.wfs20.TransactionSummaryType;

/**
 * A sample validator interface for {@link net.opengis.wfs20.TransactionResponseType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransactionResponseTypeValidator {
  boolean validate();

  boolean validateTransactionSummary(TransactionSummaryType value);
  boolean validateInsertResults(ActionResultsType value);
  boolean validateUpdateResults(ActionResultsType value);
  boolean validateReplaceResults(ActionResultsType value);
  boolean validateVersion(String value);
}
