/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import net.opengis.wfs20.AbstractTransactionActionType;
import net.opengis.wfs20.AllSomeType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.wfs20.TransactionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransactionTypeValidator {
  boolean validate();

  boolean validateGroup(FeatureMap value);
  boolean validateAbstractTransactionActionGroup(FeatureMap value);
  boolean validateAbstractTransactionAction(EList<AbstractTransactionActionType> value);
  boolean validateLockId(String value);
  boolean validateReleaseAction(AllSomeType value);
  boolean validateSrsName(String value);
}
