/**
 *
 * $Id$
 */
package net.opengis.wfs20.validation;

import java.math.BigInteger;

import java.util.Calendar;
import java.util.Collection;

import net.opengis.wfs20.AdditionalValuesType;
import net.opengis.wfs20.TruncatedResponseType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wfs20.ValueCollectionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueCollectionTypeValidator {
  boolean validate();

  boolean validateMember(EList<Collection> value);
  boolean validateAdditionalValues(AdditionalValuesType value);
  boolean validateTruncatedResponse(TruncatedResponseType value);
  boolean validateNext(String value);
  boolean validateNumberMatched(Object value);
  boolean validateNumberReturned(BigInteger value);
  boolean validatePrevious(String value);
  boolean validateTimeStamp(Calendar value);
}
