/**
 *
 * $Id$
 */
package net.opengis.wfs.validation;

import java.math.BigInteger;

import java.util.Calendar;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wfs.FeatureCollectionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureCollectionTypeValidator {
  boolean validate();

  boolean validateLockId(String value);
  boolean validateTimeStamp(Calendar value);
  boolean validateNumberOfFeatures(BigInteger value);
  boolean validateFeature(EList value);
}
