/**
 *
 * $Id$
 */
package net.opengis.wfs.validation;

import javax.xml.namespace.QName;

import net.opengis.wfs.NoSRSType;
import net.opengis.wfs.OperationsType;
import net.opengis.wfs.OutputFormatListType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wfs.FeatureTypeType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureTypeTypeValidator {
  boolean validate();

  boolean validateName(QName value);
  boolean validateTitle(String value);
  boolean validateAbstract(String value);
  boolean validateKeywords(EList value);
  boolean validateDefaultSRS(String value);
  boolean validateOtherSRS(EList value);
  boolean validateNoSRS(NoSRSType value);
  boolean validateOperations(OperationsType value);
  boolean validateOutputFormats(OutputFormatListType value);
  boolean validateWGS84BoundingBox(EList value);
  boolean validateMetadataURL(EList value);
}
