/**
 *
 * $Id$
 */
package net.opengis.wfs.validation;

import java.math.BigInteger;

import java.util.Map;

import net.opengis.wfs.ResultTypeType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wfs.GetFeatureType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GetFeatureTypeValidator {
  boolean validate();

  boolean validateQuery(EList value);
  boolean validateMaxFeatures(BigInteger value);
  boolean validateOutputFormat(String value);
  boolean validateResultType(ResultTypeType value);
  boolean validateTraverseXlinkDepth(String value);
  boolean validateTraverseXlinkExpiry(BigInteger value);
  boolean validateFormatOptions(Map value);
  boolean validateMetadata(Map value);
  boolean validateStartIndex(BigInteger value);
  boolean validateViewParams(EList value);
}
