/**
 *
 * $Id$
 */
package net.opengis.wfs.validation;

import java.net.URI;

import net.opengis.wfs.IdentifierGenerationOptionType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wfs.InsertElementType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InsertElementTypeValidator {
  boolean validate();

  boolean validateFeature(EList value);
  boolean validateHandle(String value);
  boolean validateIdgen(IdentifierGenerationOptionType value);
  boolean validateInputFormat(String value);
  boolean validateSrsName(URI value);
}
