/**
 *
 * $Id$
 */
package net.opengis.wfs.validation;

import java.net.URI;

import java.util.List;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.opengis.filter.Filter;

/**
 * A sample validator interface for {@link net.opengis.wfs.QueryType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QueryTypeValidator {
  boolean validate();

  boolean validateGroup(FeatureMap value);
  boolean validatePropertyName(EList value);
  boolean validateXlinkPropertyName(EList value);
  boolean validateFunction(EList value);
  boolean validateFilter(Filter value);
  boolean validateSortBy(EList value);
  boolean validateFeatureVersion(String value);
  boolean validateHandle(String value);
  boolean validateSrsName(URI value);
  boolean validateTypeName(List value);
}
