/**
 *
 * $Id$
 */
package net.opengis.wfs.validation;

import net.opengis.wfs.InsertResultsType;
import net.opengis.wfs.TransactionResultsType;
import net.opengis.wfs.TransactionSummaryType;

/**
 * A sample validator interface for {@link net.opengis.wfs.TransactionResponseType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransactionResponseTypeValidator {
  boolean validate();

  boolean validateTransactionSummary(TransactionSummaryType value);
  boolean validateTransactionResults(TransactionResultsType value);
  boolean validateInsertResults(InsertResultsType value);
  boolean validateVersion(String value);
}
