/**
 *
 * $Id$
 */
package net.opengis.ows20.validation;

import net.opengis.ows20.AbstractReferenceBaseType;
import net.opengis.ows20.AdditionalParameterType;
import net.opengis.ows20.AdditionalParametersType;
import net.opengis.ows20.AllowedValuesType;
import net.opengis.ows20.AnyValueType;
import net.opengis.ows20.BoundingBoxType;
import net.opengis.ows20.CodeType;
import net.opengis.ows20.ContactType;
import net.opengis.ows20.DCPType;
import net.opengis.ows20.DatasetDescriptionSummaryBaseType;
import net.opengis.ows20.DomainMetadataType;
import net.opengis.ows20.ExceptionReportType;
import net.opengis.ows20.ExceptionType;
import net.opengis.ows20.GetCapabilitiesType;
import net.opengis.ows20.GetResourceByIdType;
import net.opengis.ows20.HTTPType;
import net.opengis.ows20.KeywordsType;
import net.opengis.ows20.LanguageStringType;
import net.opengis.ows20.ManifestType;
import net.opengis.ows20.MetadataType;
import net.opengis.ows20.NilValueType;
import net.opengis.ows20.NoValuesType;
import net.opengis.ows20.OperationType;
import net.opengis.ows20.OperationsMetadataType;
import net.opengis.ows20.RangeClosureType;
import net.opengis.ows20.RangeType;
import net.opengis.ows20.ReferenceGroupType;
import net.opengis.ows20.ReferenceType;
import net.opengis.ows20.ResponsiblePartyType;
import net.opengis.ows20.ServiceIdentificationType;
import net.opengis.ows20.ServiceProviderType;
import net.opengis.ows20.ServiceReferenceType;
import net.opengis.ows20.ValueType;
import net.opengis.ows20.ValuesReferenceType;
import net.opengis.ows20.WGS84BoundingBoxType;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.ows20.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
  boolean validate();

  boolean validateMixed(FeatureMap value);
  boolean validateXMLNSPrefixMap(EMap<String, String> value);
  boolean validateXSISchemaLocation(EMap<String, String> value);
  boolean validateAbstract(LanguageStringType value);
  boolean validateAbstractMetaData(EObject value);
  boolean validateAbstractReferenceBase(AbstractReferenceBaseType value);
  boolean validateAccessConstraints(String value);
  boolean validateAdditionalParameter(AdditionalParameterType value);
  boolean validateAdditionalParameters(AdditionalParametersType value);
  boolean validateMetadata(MetadataType value);
  boolean validateAllowedValues(AllowedValuesType value);
  boolean validateAnyValue(AnyValueType value);
  boolean validateAvailableCRS(String value);
  boolean validateBoundingBox(BoundingBoxType value);
  boolean validateContactInfo(ContactType value);
  boolean validateDatasetDescriptionSummary(DatasetDescriptionSummaryBaseType value);
  boolean validateDataType(DomainMetadataType value);
  boolean validateDCP(DCPType value);
  boolean validateDefaultValue(ValueType value);
  boolean validateException(ExceptionType value);
  boolean validateExceptionReport(ExceptionReportType value);
  boolean validateExtendedCapabilities(EObject value);
  boolean validateFees(String value);
  boolean validateGetCapabilities(GetCapabilitiesType value);
  boolean validateGetResourceByID(GetResourceByIdType value);
  boolean validateHTTP(HTTPType value);
  boolean validateIdentifier(CodeType value);
  boolean validateIndividualName(String value);
  boolean validateInputData(ManifestType value);
  boolean validateKeywords(KeywordsType value);
  boolean validateLanguage(String value);
  boolean validateManifest(ManifestType value);
  boolean validateMaximumValue(ValueType value);
  boolean validateMeaning(DomainMetadataType value);
  boolean validateMinimumValue(ValueType value);
  boolean validateNilValue(NilValueType value);
  boolean validateNoValues(NoValuesType value);
  boolean validateOperation(OperationType value);
  boolean validateOperationResponse(ManifestType value);
  boolean validateOperationsMetadata(OperationsMetadataType value);
  boolean validateOrganisationName(String value);
  boolean validateOtherSource(MetadataType value);
  boolean validateOutputFormat(String value);
  boolean validatePointOfContact(ResponsiblePartyType value);
  boolean validatePositionName(String value);
  boolean validateRange(RangeType value);
  boolean validateReference(ReferenceType value);
  boolean validateReferenceGroup(ReferenceGroupType value);
  boolean validateReferenceSystem(DomainMetadataType value);
  boolean validateResource(EObject value);
  boolean validateRole(CodeType value);
  boolean validateServiceIdentification(ServiceIdentificationType value);
  boolean validateServiceProvider(ServiceProviderType value);
  boolean validateServiceReference(ServiceReferenceType value);
  boolean validateSpacing(ValueType value);
  boolean validateSupportedCRS(String value);
  boolean validateTitle(LanguageStringType value);
  boolean validateUOM(DomainMetadataType value);
  boolean validateValue(ValueType value);
  boolean validateValuesReference(ValuesReferenceType value);
  boolean validateWGS84BoundingBox(WGS84BoundingBoxType value);
  boolean validateRangeClosure(RangeClosureType value);
  boolean validateReference1(String value);
}
