/**
 *
 * $Id$
 */
package net.opengis.ows20.validation;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.w3.xlink.ActuateType;
import org.w3.xlink.ShowType;
import org.w3.xlink.TypeType;

/**
 * A sample validator interface for {@link net.opengis.ows20.MetadataType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetadataTypeValidator {
  boolean validate();

  boolean validateAbstractMetaDataGroup(FeatureMap value);
  boolean validateAbstractMetaData(EObject value);
  boolean validateAbout(String value);
  boolean validateActuate(ActuateType value);
  boolean validateArcrole(String value);
  boolean validateHref(String value);
  boolean validateRole(String value);
  boolean validateShow(ShowType value);
  boolean validateTitle(String value);
  boolean validateType(TypeType value);
}
