/**
 *
 * $Id$
 */
package net.opengis.ows20.validation;

import net.opengis.ows20.DCPType;
import net.opengis.ows20.DomainType;
import net.opengis.ows20.MetadataType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.ows20.OperationType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationTypeValidator {
  boolean validate();

  boolean validateDCP(EList<DCPType> value);
  boolean validateParameter(EList<DomainType> value);
  boolean validateConstraint(EList<DomainType> value);
  boolean validateMetadataGroup(FeatureMap value);
  boolean validateMetadata(EList<MetadataType> value);
  boolean validateName(String value);
}
