/**
 *
 * $Id$
 */
package net.opengis.ows20.validation;

import net.opengis.ows20.AllowedValuesType;
import net.opengis.ows20.AnyValueType;
import net.opengis.ows20.DomainMetadataType;
import net.opengis.ows20.MetadataType;
import net.opengis.ows20.NoValuesType;
import net.opengis.ows20.ValueType;
import net.opengis.ows20.ValuesReferenceType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.ows20.UnNamedDomainType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnNamedDomainTypeValidator {
  boolean validate();

  boolean validateAllowedValues(AllowedValuesType value);
  boolean validateAnyValue(AnyValueType value);
  boolean validateNoValues(NoValuesType value);
  boolean validateValuesReference(ValuesReferenceType value);
  boolean validateDefaultValue(ValueType value);
  boolean validateMeaning(DomainMetadataType value);
  boolean validateDataType(DomainMetadataType value);
  boolean validateUOM(DomainMetadataType value);
  boolean validateReferenceSystem(DomainMetadataType value);
  boolean validateMetadataGroup(FeatureMap value);
  boolean validateMetadata(EList<MetadataType> value);
}
