/**
 *
 * $Id$
 */
package net.opengis.ows10.validation;

import net.opengis.ows10.AddressType;
import net.opengis.ows10.OnlineResourceType;
import net.opengis.ows10.TelephoneType;

/**
 * A sample validator interface for {@link net.opengis.ows10.ContactType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContactTypeValidator {
  boolean validate();

  boolean validatePhone(TelephoneType value);
  boolean validateAddress(AddressType value);
  boolean validateOnlineResource(OnlineResourceType value);
  boolean validateHoursOfService(String value);
  boolean validateContactInstructions(String value);
}
