/**
 *
 * $Id$
 */
package net.opengis.ows10.validation;


/**
 * A sample validator interface for {@link net.opengis.ows10.ExceptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExceptionTypeValidator {
  boolean validate();

  boolean validateExceptionText(String value);
  boolean validateExceptionCode(String value);
  boolean validateLocator(String value);
}
