/**
 *
 * $Id$
 */
package net.opengis.ows10.validation;

import net.opengis.ows10.BoundingBoxType;
import net.opengis.ows10.CodeType;

import net.opengis.ows10.MetadataType;
import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.ows10.IdentificationType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IdentificationTypeValidator {
  boolean validate();

  boolean validateIdentifier(CodeType value);
  boolean validateBoundingBoxGroup(FeatureMap value);
  boolean validateBoundingBox(EList value);
  boolean validateOutputFormat(String value);
  boolean validateAvailableCRSGroup(FeatureMap value);
  boolean validateAvailableCRS(String value);
  boolean validateMetadata(EList value);
}
