<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="efeature"
    nsURI="http://geotools.org/data/efeature/efeature.ecore/1.0" nsPrefix="efeature">
  <eClassifiers xsi:type="ecore:EClass" name="EFeature" abstract="true">
    <eOperations name="getAttributeList" lowerBound="1">
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//EFeatureAttribute">
          <eTypeArguments eTypeParameter="#//EFeature/getAttributeList/V"/>
        </eTypeArguments>
      </eGenericType>
      <eTypeParameters name="V"/>
      <eParameters name="valueType">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//EFeature/getAttributeList/V"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getGeometryList" lowerBound="1">
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//EFeatureGeometry">
          <eTypeArguments eTypeParameter="#//EFeature/getGeometryList/V"/>
        </eTypeArguments>
      </eGenericType>
      <eTypeParameters name="V">
        <eBounds eClassifier="#//Geometry"/>
      </eTypeParameters>
      <eParameters name="valueType">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//EFeature/getGeometryList/V"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" defaultValueLiteral="" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SRID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" defaultValueLiteral="EPSG:4326"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" lowerBound="1" eType="#//Feature"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simple" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" volatile="true"
        defaultValueLiteral="geom">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="Doumentation" value="Name of default EFeatureGeometry"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="structure" lowerBound="1"
        eType="#//EFeatureInfo" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Feature" instanceClassName="org.opengis.feature.Feature"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Property" instanceClassName="org.opengis.feature.Property"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Attribute" instanceClassName="org.opengis.feature.Attribute"/>
  <eClassifiers xsi:type="ecore:EDataType" name="GeometryAttribute" instanceClassName="org.opengis.feature.GeometryAttribute"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Geometry" instanceClassName="com.vividsolutions.jts.geom.Geometry"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EStructureInfo" instanceClassName="org.geotools.data.efeature.EStructureInfo"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureInfo" instanceClassName="org.geotools.data.efeature.EFeatureInfo"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureAttributeInfo" instanceClassName="org.geotools.data.efeature.EFeatureAttributeInfo"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureGeometryInfo" instanceClassName="org.geotools.data.efeature.EFeatureGeometryInfo"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EStructuralFeature" instanceClassName="org.eclipse.emf.ecore.EStructuralFeature"/>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureProperty" instanceClassName="org.geotools.data.efeature.EFeatureProperty"
      serializable="false">
    <eTypeParameters name="V"/>
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Property"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureAttribute" instanceClassName="org.geotools.data.efeature.EFeatureAttribute"
      serializable="false">
    <eTypeParameters name="V"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureGeometry" instanceClassName="org.geotools.data.efeature.EFeatureGeometry"
      serializable="false">
    <eTypeParameters name="V">
      <eBounds eClassifier="#//Geometry"/>
    </eTypeParameters>
  </eClassifiers>
</ecore:EPackage>
