/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs10.validation;

import net.opengis.wcs10.ValuesType;

/**
 * A sample validator interface for {@link net.opengis.wcs10.AxisDescriptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AxisDescriptionTypeValidator {
    boolean validate();

    boolean validateValues(ValuesType value);
    boolean validateRefSys(String value);
    boolean validateRefSysLabel(String value);
    boolean validateSemantic(String value);
}
