/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs10.validation;

import net.opengis.wcs10.DomainSetType;
import net.opengis.wcs10.RangeSetType1;
import net.opengis.wcs10.SupportedCRSsType;
import net.opengis.wcs10.SupportedFormatsType;
import net.opengis.wcs10.SupportedInterpolationsType;

/**
 * A sample validator interface for {@link net.opengis.wcs10.CoverageOfferingType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoverageOfferingTypeValidator {
    boolean validate();

    boolean validateDomainSet(DomainSetType value);
    boolean validateRangeSet(RangeSetType1 value);
    boolean validateSupportedCRSs(SupportedCRSsType value);
    boolean validateSupportedFormats(SupportedFormatsType value);
    boolean validateSupportedInterpolations(SupportedInterpolationsType value);
}
