/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs10.validation;

import net.opengis.wcs10.DomainSubsetType;
import net.opengis.wcs10.InterpolationMethodType;
import net.opengis.wcs10.OutputType;
import net.opengis.wcs10.RangeSubsetType;

/**
 * A sample validator interface for {@link net.opengis.wcs10.GetCoverageType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GetCoverageTypeValidator {
    boolean validate();

    boolean validateSourceCoverage(String value);
    boolean validateDomainSubset(DomainSubsetType value);
    boolean validateRangeSubset(RangeSubsetType value);
    boolean validateInterpolationMethod(InterpolationMethodType value);
    boolean validateOutput(OutputType value);
    boolean validateService(String value);
    boolean validateVersion(String value);
}
