/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs10.validation;

import net.opengis.gml.TimePositionType;

/**
 * A sample validator interface for {@link net.opengis.wcs10.TimePeriodType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimePeriodTypeValidator {
    boolean validate();

    boolean validateBeginPosition(TimePositionType value);
    boolean validateEndPosition(TimePositionType value);
    boolean validateTimeResolution(Object value);
    boolean validateFrame(String value);
}
