/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs10.validation;

import net.opengis.wcs10.ContentMetadataType;
import net.opengis.wcs10.ServiceType;
import net.opengis.wcs10.WCSCapabilityType;

/**
 * A sample validator interface for {@link net.opengis.wcs10.WCSCapabilitiesType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WCSCapabilitiesTypeValidator {
    boolean validate();

    boolean validateService(ServiceType value);
    boolean validateCapability(WCSCapabilityType value);
    boolean validateContentMetadata(ContentMetadataType value);
    boolean validateUpdateSequence(String value);
    boolean validateVersion(String value);
}
