/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wps10.ComplexDataType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexDataTypeValidator {
  boolean validate();

  boolean validateEncoding(String value);
  boolean validateMimeType(String value);
  boolean validateSchema(String value);
  boolean validateData(EList value);
}
