/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import net.opengis.ows11.BoundingBoxType;

import net.opengis.wps10.ComplexDataType;
import net.opengis.wps10.LiteralDataType;

/**
 * A sample validator interface for {@link net.opengis.wps10.DataType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataTypeValidator {
  boolean validate();

  boolean validateComplexData(ComplexDataType value);
  boolean validateLiteralData(LiteralDataType value);
  boolean validateBoundingBoxData(BoundingBoxType value);
}
