/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import net.opengis.wps10.DescribeProcessType;
import net.opengis.wps10.ExecuteResponseType;
import net.opengis.wps10.ExecuteType;
import net.opengis.wps10.GetCapabilitiesType;
import net.opengis.wps10.LanguagesType1;
import net.opengis.wps10.ProcessDescriptionsType;
import net.opengis.wps10.ProcessOfferingsType;
import net.opengis.wps10.WPSCapabilitiesType;
import net.opengis.wps10.WSDLType;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.wps10.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
  boolean validate();

  boolean validateMixed(FeatureMap value);
  boolean validateXMLNSPrefixMap(EMap value);
  boolean validateXSISchemaLocation(EMap value);
  boolean validateCapabilities(WPSCapabilitiesType value);
  boolean validateDescribeProcess(DescribeProcessType value);
  boolean validateExecute(ExecuteType value);
  boolean validateExecuteResponse(ExecuteResponseType value);
  boolean validateGetCapabilities(GetCapabilitiesType value);
  boolean validateLanguages(LanguagesType1 value);
  boolean validateProcessDescriptions(ProcessDescriptionsType value);
  boolean validateProcessOfferings(ProcessOfferingsType value);
  boolean validateWSDL(WSDLType value);
  boolean validateProcessVersion(String value);
}
