/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import net.opengis.ows11.CodeType;

import net.opengis.wps10.DataInputsType1;
import net.opengis.wps10.ResponseFormType;

/**
 * A sample validator interface for {@link net.opengis.wps10.ExecuteType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExecuteTypeValidator {
  boolean validate();

  boolean validateIdentifier(CodeType value);
  boolean validateDataInputs(DataInputsType1 value);
  boolean validateResponseForm(ResponseFormType value);
}
