/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import net.opengis.wps10.DataInputsType1;
import net.opengis.wps10.OutputDefinitionsType;
import net.opengis.wps10.ProcessBriefType;
import net.opengis.wps10.ProcessOutputsType1;
import net.opengis.wps10.StatusType;

/**
 * A sample validator interface for {@link net.opengis.wps10.ExecuteResponseType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExecuteResponseTypeValidator {
  boolean validate();

  boolean validateProcess(ProcessBriefType value);
  boolean validateStatus(StatusType value);
  boolean validateDataInputs(DataInputsType1 value);
  boolean validateOutputDefinitions(OutputDefinitionsType value);
  boolean validateProcessOutputs(ProcessOutputsType1 value);
  boolean validateServiceInstance(String value);
  boolean validateStatusLocation(String value);
}
