/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import net.opengis.ows11.CodeType;
import net.opengis.ows11.LanguageStringType;

import net.opengis.wps10.DataType;
import net.opengis.wps10.InputReferenceType;

/**
 * A sample validator interface for {@link net.opengis.wps10.InputType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputTypeValidator {
  boolean validate();

  boolean validateIdentifier(CodeType value);
  boolean validateTitle(LanguageStringType value);
  boolean validateAbstract(LanguageStringType value);
  boolean validateReference(InputReferenceType value);
  boolean validateData(DataType value);
}
