/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import java.math.BigInteger;

import net.opengis.wps10.LiteralInputType;
import net.opengis.wps10.SupportedCRSsType;
import net.opengis.wps10.SupportedComplexDataInputType;

/**
 * A sample validator interface for {@link net.opengis.wps10.InputDescriptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputDescriptionTypeValidator {
  boolean validate();

  boolean validateComplexData(SupportedComplexDataInputType value);
  boolean validateLiteralData(LiteralInputType value);
  boolean validateBoundingBoxData(SupportedCRSsType value);
  boolean validateMaxOccurs(BigInteger value);
  boolean validateMinOccurs(BigInteger value);
}
