/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import net.opengis.ows11.AllowedValuesType;
import net.opengis.ows11.AnyValueType;

import net.opengis.wps10.ValuesReferenceType;

/**
 * A sample validator interface for {@link net.opengis.wps10.LiteralInputType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LiteralInputTypeValidator {
  boolean validate();

  boolean validateAllowedValues(AllowedValuesType value);
  boolean validateAnyValue(AnyValueType value);
  boolean validateValuesReference(ValuesReferenceType value);
  boolean validateDefaultValue(String value);
}
