/**
 *
 * $Id$
 */
package net.opengis.wps10.validation;

import net.opengis.wps10.DataInputsType;
import net.opengis.wps10.ProcessOutputsType;

/**
 * A sample validator interface for {@link net.opengis.wps10.ProcessDescriptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessDescriptionTypeValidator {
  boolean validate();

  boolean validateDataInputs(DataInputsType value);
  boolean validateProcessOutputs(ProcessOutputsType value);
  boolean validateStatusSupported(boolean value);
  boolean validateStoreSupported(boolean value);
}
