/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs11.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wcs11.CoverageSummaryType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoverageSummaryTypeValidator {
    boolean validate();

    boolean validateMetadata(EList value);
    boolean validateWGS84BoundingBox(EList value);
    boolean validateSupportedCRS(EList value);
    boolean validateSupportedFormat(EList value);
    boolean validateCoverageSummary(EList value);
    boolean validateIdentifier(String value);
    boolean validateIdentifier1(String value);
}
