/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs11.validation;

import net.opengis.wcs11.CoverageDomainType;
import net.opengis.wcs11.RangeType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.opengis.wcs11.CoverageDescriptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoverageDescriptionTypeValidator {
    boolean validate();

    boolean validateIdentifier(String value);
    boolean validateMetadata(EList value);
    boolean validateDomain(CoverageDomainType value);
    boolean validateRange(RangeType value);
    boolean validateSupportedCRS(EList value);
    boolean validateSupportedFormat(EList value);
}
