/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs11.validation;

import net.opengis.ows11.CodeType;

import net.opengis.wcs11.DomainSubsetType;
import net.opengis.wcs11.OutputType;
import net.opengis.wcs11.RangeSubsetType;

/**
 * A sample validator interface for {@link net.opengis.wcs11.GetCoverageType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GetCoverageTypeValidator {
    boolean validate();

    boolean validateIdentifier(CodeType value);
    boolean validateDomainSubset(DomainSubsetType value);
    boolean validateRangeSubset(RangeSubsetType value);
    boolean validateOutput(OutputType value);
}
