/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs11.validation;

import net.opengis.wcs11.GridCrsType;

/**
 * A sample validator interface for {@link net.opengis.wcs11.OutputType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OutputTypeValidator {
    boolean validate();

    boolean validateGridCRS(GridCrsType value);
    boolean validateFormat(String value);
    boolean validateStore(boolean value);
}
