//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.10 at 05:20:23 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geotools.org/po", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.geotools.po;
