/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 *
 *    (C) 2026, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.referencing.epsg.wkt;

import static org.junit.Assert.assertEquals;

import org.geotools.api.referencing.crs.CoordinateReferenceSystem;
import org.geotools.api.referencing.operation.MathTransform;
import org.geotools.geometry.Position2D;
import org.geotools.referencing.CRS;
import org.geotools.referencing.crs.DefaultGeographicCRS;
import org.junit.Test;

/**
 * Guards the sign of the {@code TOWGS84} rotation parameters in {@code epsg.properties}, which is generated by running
 * the EPSG database through the Bursa-Wolf synthesis of the JDBC EPSG factories: regenerating it with a build that
 * negates the wrong Coordinate Frame Rotation (EPSG 9607) parameter moves points by 79 m or more.
 *
 * <p>Expected values are golden values from PROJ 9.4.0, the same ones used by
 * {@code CoordinateFrameRotationDatumShiftTest} in the epsg-hsql module, which checks the code this file is generated
 * with:
 *
 * <pre>
 * echo "4.45 50.5" | cs2cs -f "%.9f" EPSG:4313 EPSG:4326
 * </pre>
 */
public class DatumShiftSignTest {

    /** About 10 cm, four orders of magnitude below the error a wrong rotation sign causes. */
    private static final double TOL = 1e-6;

    /** BD72, Coordinate Frame Rotation (9607), the method whose parameters need the sign conversion. */
    @Test
    public void testCoordinateFrameRotationSigns() throws Exception {
        assertShift("EPSG:4313", 4.45, 50.5, 4.451263025, 50.499444918);
    }

    /** Massawa, Geocentric Translation (9603), whose parameters are taken as stored: a control on over-negation. */
    @Test
    public void testGeocentricTranslationSigns() throws Exception {
        assertShift("EPSG:4262", 39.87, 15.23, 39.869080453, 15.229046273);
    }

    private static void assertShift(String code, double lon, double lat, double expectedLon, double expectedLat)
            throws Exception {
        CoordinateReferenceSystem source = CRS.decode(code, true);
        MathTransform transform = CRS.findMathTransform(source, DefaultGeographicCRS.WGS84);

        Position2D shifted = (Position2D) transform.transform(new Position2D(source, lon, lat), new Position2D());

        assertEquals("longitude", expectedLon, shifted.x, TOL);
        assertEquals("latitude", expectedLat, shifted.y, TOL);
    }
}
