name: Download assembly build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

jobs:
  build:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Set up GDAL
      run: |
        sudo apt update
        sudo apt install --no-install-recommends -y gdal-bin libgdal-dev libgdal-java
    - name: Maven repository caching
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          sphinx==4.5.0
          requests
    - name: Disable checksum offloading
      # See: https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760
      run: sudo ethtool -K eth0 tx off rx off
    - name: Build with Maven
      run: |
        mvn -B clean install -DskipTests -Dall -T2 --file pom.xml
    - name: Assemble downloads
      run: |
        mvn -B -DskipTests assembly:single -file release/pom.xml
    - name: Test bin download run and compile
      shell: bash
      run: |
        cd release/target
        unzip geotools-bin*.zip
        cd `ls -d geotools-*/`
        java -cp "lib/*" org.geotools.util.factory.GeoTools
        mkdir bin
        javac -cp "lib/*" -d bin src/org/geotools/tutorial/quickstart/Quickstart.java
        ls -R bin | grep Quickstart
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
