name: CQL2 online tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - uses: actions/checkout@v4
    - name: Maven repository caching
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-
    - name: Build GeoTools dependent modules (no tests, prepare fresh artifacts)
      run: mvn -B clean install -T1C -Dall --file pom.xml -DskipTests -pl :gt-cql2-text,:gt-cql2-json -am -Dspotless.apply.skip=true
    - name: Build GeoPackage module with online tests
      run: | 
        mvn -B clean install -pl :gt-cql2-text,:gt-cql2-json -Ponline -nsu -Dspotless.apply.skip=true
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {} 
