name: ElasticSearch integration tests JDK 11

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'temurin'
    - uses: actions/checkout@v2
    - name: Maven repository caching
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-
    - name: Build GeoTools dependent modules (no tests, prepare fresh artifacts)
      run: mvn -B clean install -T2 -Dall --file pom.xml -DskipTests -pl modules/unsupported/elasticsearch -am
    - name: Build ElasticSearch module with online tests, using the OSS version 
      run: | 
        mvn -B clean install --file modules/unsupported/elasticsearch/pom.xml -Ponline -nsu
    - name: Build ElasticSearch module with online tests, using the non OSS version
      run: | 
        mvn -B clean install --file modules/unsupported/elasticsearch/pom.xml -Ponline -nsu -Delastic.test.image=docker.elastic.co/elasticsearch/elasticsearch -Delastic.test.version=7.15.2
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {} 
