name: Informix online tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        java: [17]

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - name: Maven repository caching
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: gt-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            gt-maven-
      - name: Setup test environment for Informix
        run: |
          ./build/ci/informix/start-informix.sh
          ./build/ci/informix/setup-informix.sh
      - name: Build GeoTools dependent modules (no tests)
        run: mvn -B clean install -T1C -Dall -pl :gt-jdbc-informix -DskipTests -am -Dspotless.apply.skip=true
      - name: Test Informix data store
        run: mvn -B verify -pl :gt-jdbc-informix -Ponline -Dspotless.apply.skip=true
      - name: Remove SNAPSHOT jars from repository
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
