name: Linux GDAL GitHub CI

on: [pull_request]

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

jobs:
  build:
    runs-on: [ubuntu-22.04]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Set up GDAL
      run: |
        sudo apt update
        sudo apt install --no-install-recommends -y gdal-bin libgdal-dev
        # From OSGeo live
        URL="http://download.osgeo.org/livedvd/data/gdal/gdal-3.4.3+dfsg-java.20220622.tgz"
        FILE=/tmp/$(basename "$URL")
        wget --no-verbose -O "$FILE" "$URL" && \
        sudo tar xvf "$FILE" -C /
        sudo mv /usr/lib/jni/libgdalalljni.so /usr/lib
    - name: Maven repository caching
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-
    - name: Disable checksum offloading
      # See: https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760
      run: sudo ethtool -K eth0 tx off rx off
    - name: Build with Maven
      run: |
        mvn -B clean install -Dspotless.apply.skip=true -Dall -U --file pom.xml -pl :gt-imageio-ext-gdal,:gt-ogr -am
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
